export const IPC_CHANNELS = {
  AUTH_GET_SESSION: "auth:get-session",
  AUTH_GET_PROVIDERS: "auth:get-providers",
  AUTH_GET_REGIONS: "auth:get-regions",
  AUTH_LOGIN: "auth:login",
  AUTH_LOGOUT: "auth:logout",
  SUBSCRIPTION_FETCH: "subscription:fetch",
  GAMES_FETCH_MAIN: "games:fetch-main",
  GAMES_FETCH_LIBRARY: "games:fetch-library",
  GAMES_FETCH_PUBLIC: "games:fetch-public",
  GAMES_RESOLVE_LAUNCH_ID: "games:resolve-launch-id",
  CREATE_SESSION: "gfn:create-session",
  POLL_SESSION: "gfn:poll-session",
  STOP_SESSION: "gfn:stop-session",
  GET_ACTIVE_SESSIONS: "gfn:get-active-sessions",
  CLAIM_SESSION: "gfn:claim-session",
  SESSION_CONFLICT_DIALOG: "gfn:session-conflict-dialog",
  CONNECT_SIGNALING: "gfn:connect-signaling",
  DISCONNECT_SIGNALING: "gfn:disconnect-signaling",
  SEND_ANSWER: "gfn:send-answer",
  SEND_ICE_CANDIDATE: "gfn:send-ice-candidate",
  SIGNALING_EVENT: "gfn:signaling-event",
  TOGGLE_FULLSCREEN: "window:toggle-fullscreen",
  TOGGLE_POINTER_LOCK: "window:toggle-pointer-lock",
  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_RESET: "settings:reset",
  LOGS_EXPORT: "logs:export",
  LOGS_GET_RENDERER: "logs:get-renderer",
  DISCORD_UPDATE_PRESENCE: "discord:update-presence",
  DISCORD_CLEAR_PRESENCE: "discord:clear-presence",
  FLIGHT_GET_PROFILE: "flight:get-profile",
  FLIGHT_SET_PROFILE: "flight:set-profile",
  FLIGHT_DELETE_PROFILE: "flight:delete-profile",
  FLIGHT_GET_ALL_PROFILES: "flight:get-all-profiles",
  FLIGHT_RESET_PROFILE: "flight:reset-profile",
  HDR_GET_OS_INFO: "hdr:get-os-info",
  MIC_ENUMERATE_DEVICES: "mic:enumerate-devices",
  MIC_DEVICES_CHANGED: "mic:devices-changed",
  APP_RELAUNCH: "app:relaunch",
  AUTH_SESSION_EXPIRED: "auth:session-expired",
  GET_PLATFORM_INFO: "app:get-platform-info",} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
